// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPower.Data;

namespace Encoder.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200307204602_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Encoder.Data.Tables.GenericReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Length");

                    b.Property<int>("LineId");

                    b.Property<string>("MachineId");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("GenericReadings");
                });

            modelBuilder.Entity("SmartPower.Data.Tables.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Assignment");

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("LastRequest");

                    b.Property<decimal>("Length");

                    b.Property<int>("LineId");

                    b.Property<string>("MachineId");

                    b.Property<string>("PairId");

                    b.Property<DateTime>("StartTime");

                    b.Property<short>("Status");

                    b.HasKey("Id");

                    b.ToTable("LengthReadings");
                });

            modelBuilder.Entity("SmartPower.Data.Tables.ReadingsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Assignment");

                    b.Property<DateTime>("EndTime");

                    b.Property<decimal>("Length");

                    b.Property<int>("LineId");

                    b.Property<string>("MachineId");

                    b.Property<string>("PairId");

                    b.Property<DateTime>("StartTime");

                    b.Property<short>("Status");

                    b.HasKey("Id");

                    b.ToTable("LengthReadingsLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
